### ISSUE TITLE
Crash on server start with forge 1.16

### ISSUE THREAD

**Issue by alexlambson** [Judge40/BetterMobGriefingGameRule#30]
I attempted to install the alpha to a 1.16 forge server and the output said their was missing file info and crashed.

```
---- Minecraft Crash Report ----
// There are four lights!
Time: 10/18/20 9:50 PM
Description: Mod loading error has occurred
java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[?:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:96) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?] {}
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[?:?] {re:classloading}
-- NO MOD INFO AVAILABLE --
Details:
	Mod File: NO FILE INFO
	Failure message: Missing License Information in file Mod File: F:\Minecraft\Server Manager v11.8.3\servers\Forge\mods\bettermobgriefinggamerule-1.16.1-8.0.2-alpha.jar
	Mod Version: NO MOD INFO AVAILABLE
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[?:?] {re:classloading}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_191] {}
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[?:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:96) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?] {}
-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 395712536 bytes (377 MB) / 1354235904 bytes (1291 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xms256M -Xmx4096M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.1.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.1.jar mixin TRANSFORMATIONSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.0
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.0-server.jar Minecraft {minecraft@1.16.3 NONE}
		bettermobgriefinggamerule-1.16.1-8.0.2-alpha.jar Better mobGriefing GameRule {bettermobgriefinggamerule@1.16.1-8.0.2-alpha NONE}
		FriendlyFire-1.16.3-5.0.3.jar FriendlyFire {friendlyfire@5.0.3 NONE}
		forge-1.16.3-34.1.0-universal.jar Forge {forge@34.1.0 NONE}
		FastFurnace-1.16.3-4.3.0.jar FastFurnace {fastfurnace@4.3.0 NONE}
		Xaeros_Minimap_20.25.0_Forge_1.16.3.jar Xaero's Minimap {xaerominimap@20.25.0 NONE}
		Waystones_1.16.3-7.3.0.jar Waystones {waystones@7.3.0 NONE}
		upsizer-mc1.16.3-6.0.jar Upsizer {upsizer@6.0 NONE}
		ftb-backups-2.1.1.6.jar FTB Backups {ftbbackups@2.1.1.6 NONE}
		Clumps-6.0.0.11.jar Clumps {clumps@6.0.0.11 NONE}
		XaerosWorldMap_1.11.0_Forge_1.16.3.jar Xaero's World Map {xaeroworldmap@1.11.0 NONE}
		Placebo-1.16.3-4.3.1.jar Placebo {placebo@4.3.1 NONE}
		RepairChests-1.16.3-1.5.jar Repair Chests {repairchests@1.5 NONE}[1;31m[21:50:38] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Missing License Information in file Mod File: F:\Minecraft\Server Manager v11.8.3\servers\Forge\mods\bettermobgriefinggamerule-1.16.1-8.0.2-alpha.jar
]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:177) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[?:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:96) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?] {}
```

I am wondering if the build pipeline missed the license file. I'd put up a PR to add it, but I don't know what you want your license to look like.

**Comment by alexlambson** [comment]
Low priority since forge reverted this requirement in v33

**Comment by Judge40** [comment]
Thanks for the report, I had a an unreleased fix for this that I've just released as  [1.16.1-8.0.3-beta](https://github.com/Judge40/BetterMobGriefingGameRule/releases/tag/1.16.1-8.0.3-beta)

**Comment by alexlambson** [comment]
Ah okay, sorry for the false issue. Thank you :)

**Comment by Judge40** [comment]
> Ah okay, sorry for the false issue. Thank you :)

No problem at all, it gave me the reminder that I needed to publish the changes.
