### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by Alonlystalker** [Judge40/BetterMobGriefingGameRule#32]
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.judge40.minecraft.bettermobgriefinggamerule.common.MobGriefingEventHandler.isMobGriefingEnabled(MobGriefingEventHandler.java:81) ~[bettermobgriefinggamerule:?] {re:classloading}
	at com.judge40.minecraft.bettermobgriefinggamerule.common.MobGriefingEventHandler.onMobGriefing(MobGriefingEventHandler.java:50) ~[bettermobgriefinggamerule:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_163_MobGriefingEventHandler_onMobGriefing_EntityMobGriefingEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.getMobGriefingEvent(ForgeEventFactory.java:691) ~[forge:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:743) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:688) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:buzzier_bees.mixins.json:MobEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMobEntity,pl:mixin:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:astralsorcery:water_movement_slowdown_prevention,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinLivingEntity,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinLivingEntity_C,pl:mixin:APP:imm_ptl_mixins.json:client.MixinLivingEntity_C,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:buzzier_bees.mixins.json:MobEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMobEntity,pl:mixin:A}
	at net.minecraft.entity.monster.CreeperEntity.func_70071_h_(CreeperEntity.java:150) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorCreeperEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.37.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.judge40.minecraft.bettermobgriefinggamerule.common.MobGriefingEventHandler.isMobGriefingEnabled(MobGriefingEventHandler.java:81) ~[bettermobgriefinggamerule:?] {re:classloading}
	at com.judge40.minecraft.bettermobgriefinggamerule.common.MobGriefingEventHandler.onMobGriefing(MobGriefingEventHandler.java:50) ~[bettermobgriefinggamerule:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_163_MobGriefingEventHandler_onMobGriefing_EntityMobGriefingEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.getMobGriefingEvent(ForgeEventFactory.java:691) ~[forge:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:743) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:688) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:buzzier_bees.mixins.json:MobEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMobEntity,pl:mixin:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:astralsorcery:water_movement_slowdown_prevention,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinLivingEntity,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinLivingEntity_C,pl:mixin:APP:imm_ptl_mixins.json:client.MixinLivingEntity_C,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:buzzier_bees.mixins.json:MobEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMobEntity,pl:mixin:A}
	at net.minecraft.entity.monster.CreeperEntity.func_70071_h_(CreeperEntity.java:150) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorCreeperEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}
-- Entity being ticked --
Details:
	Entity Type: minecraft:creeper (net.minecraft.entity.monster.CreeperEntity)
	Entity ID: 198
	Entity Name: Creeper
	Entity's Exact location: -465.50, 56.00, 1525.50
	Entity's Block location: World: (-466,56,1525), Chunk: (at 14,3,5 in -30,95; contains blocks -480,0,1520 to -465,255,1535), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}

**Comment by Judge40** [comment]
@Alonlystalker Could you confirm which version you're seeing this on?

I have identified a potential issue and done what I can to resolve it. `1.16.3-8.0.4-beta` has been released for the `1.16.x` stream, let me know if you are using a different Minecraft version and I can backport the changes.

**Comment by Alonlystalker** [comment]
i'll get it on 1.16.4 forge 35.1.37 but with latest version of the mod all fine, so thanks for fast bugfix.
